= QUICKSTART KATA POKER


== TDD

All kata should be made following TDD practices:

- RED
- GREEN
- REFACTOR

== Code provided
Just as  a quickstart for tests (avoid to create many boring code) and to have  common names
Code provided is :

- 2 enums for colors & ranks
- what is a card
- a few testing hands (should cover most of the tests)

== Playing the kata
For each new exercise :

- create the test
- make the code compile
- relaunch the tests
- refactor if needed


== Working withe kata
This repository will remain stable and you should not commit to this repository (you can’t) So please use the following strategy:
fork the original repository
work on this repository as needed (commit locally and then push to your remote)
if you want to see someone else work then use the github widget to find all other forks
then add as a remote repository the targeted fork
Now you can get solutions from other repositories and use Intellij or git diff features to see how other developers code this kata.
So no need to push to the main repository & no need to send PRs …​ Doing this is like contributing to open source software (it is one of the possible workflows)
I would like to see many forks..